# Title of the app (shown on top left)
main_title: "RESQUE UWH"

# Background color of the app
background_color: "#ffffee"

# Maximum number of papers that are expected by the committee
max: 3

# Number of top papers that must be selected
max_top_papers: 0

# Minimum number of papers that must be entered before 
# showing a warning is shown at the scoring box
min_RO_warning_threshold: 0

# Show the welcome message (text is defined in config/instructions.md)
show_instruction: false

# Show the beta warning message
show_beta_warning: false

# Logo
image_url: https://s7g10.scene7.com/is/image/heliosgesundheit/UNI-witten-herdecke

hide_score: false

meta:
  sources: ["packs/core-meta.json"]
  exclude: ["AcademicAgeBonus", "AcademicAgeBonus_Explanation", "HonestyDisclaimer", "M_MeritStatement_Info", "MeritStatement", "METASEP0"]
  config:
    min_indicators_warning_threshold: 0

pubs:
  sources: ["packs/core-pubs.json"]
  exclude: ["P_CRediT_Info", "P_CRediT_InJournal", "P_CRediT", "P8P9bSEP", "P_TopPaper", "P_Stimuli", "P_Sample_RepresentativenessRelevance", "P_Sample_Representative", "P_Sample_Representative_Details", "P_MultiStudy_Note2", "P_Power_Info", "P_PowerConsiderations", "P_SampleSize", "P_MeritStatement_Info", "P_MeritStatement", "P_ImpactStatement_Info", "P_ImpactStatement", "P_Theorizing", "P17P18SEP", "P19P20SEP", "P22P23SEP", "P23P24SEP"]
  config:
    min_indicators_warning_threshold: 0

data:
  sources: ["packs/core-data.json"]
  config:
    min_indicators_warning_threshold: 0

software:
  sources: ["packs/core-software.json"]
  config:
    min_indicators_warning_threshold: 0

score_categories:
  - title: "Open Data"
    cue: "Data"
    color: '#beaed4'

  - title: "Open Materials"
    cue: "OpenMaterials"
    color: '#fdc086'

  - title: "Preregistration"
    cue: "Prereg"
    color: '#d95f02'

  - title: "Reproducible Code & Verification"
    cue: "ReproducibleScripts|IndependentVerification"
    color: '#386cb0'

  # - title: "Methodological Rigor"
  #   cue: "_Methods_"
  #   color: '#f0027f'

  # - title: "Theorizing & Formal Modeling"
  #   cue: "Theorizing"
  #   color: '#7fc97f'
